contact_links:
  - name: 📚 Documentation
    url: https://maze-technology.github.io/
    about: Read the docs for common questions and usage guides.
  - name: 💬 Discord
    url: https://discord.gg/66Xr8BAfPE
    about: For help, questions, or general discussion, visit our Discord.
